### PR TITLE
Add credits to original author back

### PR DESCRIPTION
**Pull request by ijsKoud**
Hello there,

I am the original author of this project and I noticed that this repo is violating the terms of the license. While it still has my name in the license file, it also needs a backlink to me as original author somewhere else more visible. The only thing added back is the author section on the readme, nothing more.

### CODE REVIEW

**Comment by lamettrist** [comment]
Hey luxxy,
go credit this man. I was able to verify that is repo is an exact clone of DaanGames' git repo.

**Comment by Luxxy-GF** [comment]
This Repo only for cloning the repo on a egg I had to modify it to use the right stuff for the egg also added landing page i not going to add files because it will show on the file manager

**Comment by ijsKoud** [comment]
It does not matter that it shows up in the fs, it matters that the original author is credited.

You did not even fork the repo, if that was the case then I would have let it slip but seeing as you did not do that and removed the credits aswell it is still violating the terms.

edit: I noticed a backlink to my repo in the desc, that is acceptable but look at the comment below too

**Comment by ijsKoud** [comment]
Another thing, As the license states, the original license with the original author should always be in the distributed/copied contents, otherwise I can file a DMCA take down which I will

**Comment by Luxxy-GF** [comment]
as i said i only edit the repo to clone to the egg that won't need the read me and stuff like that reason why removed

**Pull request closed without merging**
